### ISSUE TITLE
isRunning 这个属性显示是否正在推流，但是经常给的错误信息，比如没有在推流（用服务器查的），isRunning却显示在推流。

### ISSUE THREAD

**Issue by sunkuo** [pili-engineering/PLAudioStreamingKit#6]

**Comment by Phunk87** [comment]
> 该状态表达的是 streamingSession 有没有开始推流。当 streamState 为 PLStreamStateConnecting 或者 PLStreamStateConnected 时, isRunning 都会为 YES，所以它为 YES 时并不表示流一定已经建立连接，其从广义上表达 streamingSession 作为客户端对象的状态。

在 1.1.5 中，有添加说明的注释
